/**
 * Catálogo padrão de contingência da Conflora Horta e Viveiro.
 * Utilizado quando a conexão com o Google Sheets não possui credenciais ativas em ambiente local.
 */
const DEFAULT_CATALOG_ITEMS = [
  {
    id: '1',
    name: 'Palmeira Rabo de Raposa',
    category: 'Plantas / Mudas',
    subcategory: 'Palmeiras',
    price: 79.0,
    status: 'ATIVO',
    imageFileId: 'drive-file-rabo-de-raposa-01',
    descriptionAi: 'Palmeira ornamental de crescimento rápido para sol pleno.',
    tagsAi: 'rabo de raposa, wodyetia bifurcata, palmeira australiana',
  },
  {
    id: '2',
    name: 'Palmeira Rabo de Raposa',
    category: 'Plantas / Mudas',
    subcategory: 'Palmeiras',
    price: 195.0,
    status: 'ATIVO',
    imageFileId: 'drive-file-rabo-de-raposa-02',
    descriptionAi: 'Muda grande 2 metros.',
    tagsAi: 'rabo de raposa, muda grande',
  },
  {
    id: '3',
    name: 'Palmeira Azul',
    category: 'Plantas / Mudas',
    subcategory: 'Palmeiras',
    price: 190.0,
    status: 'ATIVO',
    descriptionAi: 'Palmeira imponente de folhas azul-acinzentadas para jardins.',
    tagsAi: 'bismarckia nobilis, palmeira bismarckia, palmeira de bismarck',
  },
  {
    id: '4',
    name: 'Areca Bambu',
    category: 'Plantas / Mudas',
    subcategory: 'Palmeiras',
    price: 79.0,
    status: 'ATIVO',
    tagsAi: 'dypsis lutescens, areca',
  },
  {
    id: '5',
    name: 'Bouganville / Primavera',
    category: 'Plantas / Mudas',
    subcategory: 'Trepadeiras e pendentes',
    price: 59.0,
    status: 'ATIVO',
    tagsAi: 'tres marias, três marias, flor de papel',
    descriptionAi: 'Trepadeira muito florida de sol pleno.',
  },
  {
    id: '6',
    name: 'MINI CABRA MACHO',
    category: 'Pets',
    subcategory: 'Pequenos mamíferos',
    price: 2900.0,
    status: 'ATIVO',
    tagsAi: 'mini cabra, bode anao, caprino',
  },
  {
    id: '7',
    name: 'MINI CABRA FÊMEA',
    category: 'Pets',
    subcategory: 'Pequenos mamíferos',
    price: 3900.0,
    status: 'ATIVO',
    tagsAi: 'mini cabra, cabritinha, caprino',
  },
  {
    id: '8',
    name: 'ALFACE CRESPA',
    category: 'Horta',
    subcategory: 'Folhosas',
    price: 8.0,
    status: 'ATIVO',
  },
  {
    id: '9',
    name: 'ALFACE CRESPA',
    category: 'Horta',
    subcategory: 'Folhosas',
    price: 14.0,
    status: 'ATIVO',
  },
  {
    id: '10',
    name: 'ALFACE CRESPA',
    category: 'Horta',
    subcategory: 'Folhosas',
    price: 20.0,
    status: 'ATIVO',
  },
  {
    id: '11',
    name: 'ALFACE CABEÇA / AMERICANA',
    category: 'Horta',
    subcategory: 'Folhosas',
    price: 8.0,
    status: 'ATIVO',
  },
  {
    id: '12',
    name: 'RÚCULA',
    category: 'Horta',
    subcategory: 'Folhosas',
    price: 8.0,
    status: 'ATIVO',
  },
  {
    id: '13',
    name: 'CEBOLINHA',
    category: 'Horta',
    subcategory: 'Temperos e ervas',
    price: 8.0,
    status: 'ATIVO',
  },
];

module.exports = {
  DEFAULT_CATALOG_ITEMS,
};
