#!/usr/bin/env bash
set -euo pipefail

PROJECT_ID="${PROJECT_ID:-conflora-ai}"
REGION="${REGION:-southamerica-east1}"
SERVICE_NAME="${SERVICE_NAME:-conflora-api}"
RUNTIME_SA_NAME="${RUNTIME_SA_NAME:-conflora-api-sa}"
RUNTIME_SA="${RUNTIME_SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"
QUEUE="${QUEUE:-conflora-jobs}"
SHEET_NAME="${SHEET_NAME:-PRODUTOS}"
FOLLOWUP_SECONDS="${FOLLOWUP_SECONDS:-3600}"
GEMINI_LOCATION="${GEMINI_LOCATION:-global}"
GEMINI_MODEL="${GEMINI_MODEL:-gemini-3.7-flash}"
WHATSAPP_TEMPLATE_LANGUAGE="${WHATSAPP_TEMPLATE_LANGUAGE:-pt_BR}"

: "${SPREADSHEET_ID:?Defina SPREADSHEET_ID}"
: "${SERVICE_URL:?Defina SERVICE_URL}"
: "${WHATSAPP_GRAPH_VERSION:?Defina WHATSAPP_GRAPH_VERSION}"
: "${WHATSAPP_PHONE_NUMBER_ID:?Defina WHATSAPP_PHONE_NUMBER_ID}"
: "${OWNER_WHATSAPP_NUMBER:?Defina OWNER_WHATSAPP_NUMBER}"
: "${PIX_KEY:?Defina PIX_KEY}"
: "${PIX_TITULAR:?Defina PIX_TITULAR}"

gcloud config set project "$PROJECT_ID" >/dev/null

gcloud run deploy "$SERVICE_NAME" \
  --source . \
  --region "$REGION" \
  --allow-unauthenticated \
  --service-account "$RUNTIME_SA" \
  --min 1 \
  --update-env-vars="NODE_ENV=production,GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=$REGION,GEMINI_LOCATION=$GEMINI_LOCATION,GEMINI_MODEL=$GEMINI_MODEL,SPREADSHEET_ID=$SPREADSHEET_ID,SHEET_NAME=$SHEET_NAME,SHEETS_CACHE_SECONDS=60,CLOUD_TASKS_QUEUE=$QUEUE,SERVICE_URL=$SERVICE_URL,FOLLOWUP_SECONDS=$FOLLOWUP_SECONDS,WHATSAPP_GRAPH_VERSION=$WHATSAPP_GRAPH_VERSION,WHATSAPP_PHONE_NUMBER_ID=$WHATSAPP_PHONE_NUMBER_ID,OWNER_WHATSAPP_NUMBER=$OWNER_WHATSAPP_NUMBER,PIX_KEY=$PIX_KEY,PIX_TITULAR=$PIX_TITULAR,OWNER_ORDER_TEMPLATE=nova_venda_conflora,OWNER_RECEIPT_IMAGE_TEMPLATE=comprovante_pix_imagem,OWNER_RECEIPT_DOCUMENT_TEMPLATE=comprovante_pix_documento,WHATSAPP_TEMPLATE_LANGUAGE=$WHATSAPP_TEMPLATE_LANGUAGE" \
  --update-secrets="WHATSAPP_TOKEN=whatsapp-token:latest,WHATSAPP_VERIFY_TOKEN=whatsapp-verify-token:latest,META_APP_SECRET=meta-app-secret:latest,TASK_SECRET=conflora-task-secret:latest,ADMIN_SECRET=conflora-admin-secret:latest"
